### ISSUE TITLE
TF1s are not properly handled. The formula should be taken from its TFormula member (if any). A failing example will follow soon

### ISSUE THREAD

**Issue by bellenot** [root-project/jsroot#127]

**Comment by linev** [comment]
Here is code which handles TFormula in TF1:

https://github.com/root-project/jsroot/blob/master/scripts/JSRootCore.js#L1540-L1544

I can imagine, that many use-cases are not covered

**Comment by linev** [comment]
Seems to be, TFormula was changed once again.
Now function in TFormula saved in format which is about the same as in ROOT5.
At least here:

http://jsroot.gsi.de/dev/?file=../files/tmp/c1.root&item=c1

This is canvas, produced in tutorials/fit/fit1.C macro.

Now fixed in master and dev branches.
I hope, TF1 will work again.

**Comment by bellenot** [comment]
Thanks Sergey (I was about to commit a patch too...).

**Comment by linev** [comment]
Sorry.

**Comment by bellenot** [comment]
No problem, thanks for fixing it!
